### PR TITLE
Enable proxy protocol for aws load balancer

### PR DESCRIPTION
**Pull request by erkannt**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
https://alfred.elifesciences.org/job/test-libero-reviewer/ is still applying `master` on every Docker image push so I get will apply this change when merged, too.

**Comment by diversemix** [comment]
Leave it with you two @erkannt / @giorgiosironi  .... let me know if you need another review?

**Comment by erkannt** [comment]
Testcase:

client > aws loadbalancer > reviewer-client nginx > reviewer-submission


- orig. client IP shows up in nginx logs of reviewer-client using x-forwarded-for
- same shows up in reviewer-submission

**Comment by erkannt** [comment]
Log snippets before merge on reviewer-client:

```
12:25:58.352453 IP (tos 0x0, ttl 255, id 45136, offset 0, flags [DF], proto TCP (6), length 667)
    libero-reviewer--staging-client-7fd6649bb5-k5rns.52410 > libero-reviewer--staging-submission.default.svc.cluster.local.3000: Flags [P.], cksum 0x5
e6f (incorrect -> 0x5ecc), seq 1:616, ack 1, win 211, options [nop,nop,TS val 3762972161 ecr 3831621445], length 615
E....P@...m*
..............#...<....^o.....
.Jf..a.EGET /graphql HTTP/1.1
X-Forwarded-For: 10.0.11.30
Host: libero-reviewer--staging.elifesciences.org
Upgrade: websocket
Connection: upgrade
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0
Accept: */*
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
Sec-WebSocket-Version: 13
Origin: https://libero-reviewer--staging.elifesciences.org
Sec-WebSocket-Protocol: graphql-ws
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: qXghRKcL6Doodq713/fVSw==
Cookie: cookieNotificationAccepted=true
Pragma: no-cache
Cache-Control: no-cache

12:25:56.708407 IP (tos 0x0, ttl 253, id 36059, offset 0, flags [DF], proto TCP (6), length 571)
    ip-10-0-11-191.ec2.internal.51812 > libero-reviewer--staging-client-7fd6649bb5-k5rns.9000: Flags [P.], cksum 0xe947 (correct), seq 1:520, ack 1, w
in 106, options [nop,nop,TS val 250444097 ecr 2385536051], length 519
E..;..@....1
...
....d#(yL..b@.h...j.G.....
..yA.0d3GET /login HTTP/1.1
Host: libero-reviewer--staging.elifesciences.org
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: cookieNotificationAccepted=true
Upgrade-Insecure-Requests: 1
If-Modified-Since: Wed, 08 Apr 2020 16:35:13 GMT
If-None-Match: "5e8dfd41-7c49"
Cache-Control: max-age=0

```

**Comment by erkannt** [comment]
After merge I'm getting 400 bad request.

But my IP is showing up in the logs:

```
10.0.12.39 - - [09/Apr/2020:12:39:53 +0000] "PROXY TCP4 81.131.179.14 10.0.12.54 42642 443" 400 157 "-" "-"
10.0.12.39 - - [09/Apr/2020:12:39:53 +0000] "PROXY TCP4 10.0.12.54 10.0.12.54 3926 31499" 400 157 "-" "-"
10.0.11.191 - - [09/Apr/2020:12:39:56 +0000] "PROXY TCP4 10.0.11.23 10.0.11.23 41104 31499" 400 157 "-" "-"
10.0.11.30 - - [09/Apr/2020:12:39:56 +0000] "PROXY TCP4 10.0.11.23 10.0.11.23 19212 31499" 400 157 "-" "-"

```

**Pull request merged**
